version: '3.7'

services:
  honeygain:
    image: honeygain/honeygain
    environment:
     - HONEYGAIN_EMAIL
     - HONEYGAIN_PASSWORD
     - HONEYGAIN_DEVICE
    restart: always
    command: -tou-accept -email ${HONEYGAIN_EMAIL} -pass ${HONEYGAIN_PASSWORD} -device ${HONEYGAIN_DEVICE}

  pawns:
    image: iproyal/pawns-cli
    environment:
     - PAWNS_EMAIL
     - PAWNS_PASSWORD
     - PAWNS_DEVICE
    restart: always
    command: -accept-tos -email=${PAWNS_EMAIL} -password=${PAWNS_PASSWORD} -device-name=${PAWNS_DEVICE}
